spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password:
    tomcat:
      validation-query: SELECT 1
      test-while-idle: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080
